// Local autocorrect: static dictionary lookup on word boundary.
// No API calls. Deterministic. Conservative — only fires on lowercase, non-name-shaped words.
//
// Override rule: if the user has the same word elsewhere in the doc,
// we treat it as intentional and skip the correction. This means:
//   - First typo gets fixed.
//   - If you Ctrl+Z to undo, the original is back in the text → future typings stay.
//   - If you manually type the original word elsewhere → future typings stay.

const WORD_RE = /[a-zA-Z']/;

const BOUNDARY = new Set([
  ' ',
  '\t',
  '\n',
  '\r',
  '.',
  ',',
  ';',
  ':',
  '!',
  '?',
  ')',
  ']',
  '}',
  '/',
  '\\',
  '-'
]);

export function isWordBoundary(ch: string): boolean {
  return BOUNDARY.has(ch);
}

export interface Correction {
  newText: string;
  newCursor: number;
  from: string;
  to: string;
  start: number;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function autoCorrectBeforeBoundary(
  text: string,
  cursor: number
): Correction | null {
  if (cursor <= 0) return null;
  let end = cursor;
  let start = end;
  while (start > 0 && WORD_RE.test(text[start - 1] ?? '')) start--;
  const word = text.slice(start, end);
  if (!word || word.length < 2) return null;

  // Conservative gates — protect names, codes, abbreviations.
  if (word !== word.toLowerCase()) return null;
  if (/[0-9]/.test(word)) return null;

  const correction = TYPOS[word];
  if (!correction || correction === word) return null;

  // Override: if the user has the same word elsewhere in the doc, respect it.
  const before = text.slice(0, start);
  const after = text.slice(end);
  const wordRegex = new RegExp(`\\b${escapeRegex(word)}\\b`, 'i');
  if (wordRegex.test(before) || wordRegex.test(after)) return null;

  const newText = before + correction + after;
  const newCursor = start + correction.length;
  return { newText, newCursor, from: word, to: correction, start };
}

// Curated dictionary. Keys MUST be lowercase. Conservative — words that are
// almost never intentional spellings.
export const TYPOS: Record<string, string> = {
  // Solo lowercase "i"
  i: 'I',

  // Contractions (skipped: ill, id, well, wed, lets, its, were — all ambiguous)
  dont: "don't",
  dosent: "doesn't",
  doesnt: "doesn't",
  didnt: "didn't",
  cant: "can't",
  couldnt: "couldn't",
  shouldnt: "shouldn't",
  wouldnt: "wouldn't",
  wont: "won't",
  isnt: "isn't",
  arent: "aren't",
  wasnt: "wasn't",
  werent: "weren't",
  havent: "haven't",
  hasnt: "hasn't",
  hadnt: "hadn't",
  im: "I'm",
  ive: "I've",
  youre: "you're",
  youve: "you've",
  youll: "you'll",
  theyre: "they're",
  theyve: "they've",
  theyll: "they'll",
  theyd: "they'd",
  weve: "we've",
  thats: "that's",
  hes: "he's",
  shes: "she's",
  heres: "here's",
  theres: "there's",
  wheres: "where's",
  hows: "how's",
  whens: "when's",
  whys: "why's",
  whats: "what's",
  whos: "who's",
  shouldve: "should've",
  couldve: "could've",
  wouldve: "would've",
  mustve: "must've",
  mightve: "might've",

  // Top common typos
  teh: 'the',
  hte: 'the',
  het: 'the',
  thge: 'the',
  thier: 'their',
  adn: 'and',
  nad: 'and',
  wiht: 'with',
  witht: 'with',
  whit: 'with',
  htat: 'that',
  thsi: 'this',
  thsis: 'this',
  becuase: 'because',
  becasue: 'because',
  becuse: 'because',
  becouse: 'because',
  becauce: 'because',
  recieve: 'receive',
  recieved: 'received',
  recieving: 'receiving',
  reciept: 'receipt',
  recipt: 'receipt',
  seperate: 'separate',
  seperated: 'separated',
  seperately: 'separately',
  seperating: 'separating',
  occured: 'occurred',
  occuring: 'occurring',
  occurence: 'occurrence',
  occurances: 'occurrences',
  ocurr: 'occur',
  definately: 'definitely',
  definatly: 'definitely',
  defintely: 'definitely',
  definetly: 'definitely',
  defiantly: 'definitely',
  neccessary: 'necessary',
  neccesary: 'necessary',
  necesary: 'necessary',
  necassary: 'necessary',
  accomodate: 'accommodate',
  accomodating: 'accommodating',
  accomodation: 'accommodation',
  acheive: 'achieve',
  acheived: 'achieved',
  acheiving: 'achieving',
  achievment: 'achievement',
  adress: 'address',
  addres: 'address',
  arguement: 'argument',
  arguements: 'arguments',
  beleive: 'believe',
  beleived: 'believed',
  beleiving: 'believing',
  beleif: 'belief',
  buisness: 'business',
  buisnesses: 'businesses',
  calender: 'calendar',
  calander: 'calendar',
  catagory: 'category',
  catagories: 'categories',
  cemetary: 'cemetery',
  collegue: 'colleague',
  collegues: 'colleagues',
  comming: 'coming',
  becomming: 'becoming',
  commitee: 'committee',
  commited: 'committed',
  commiting: 'committing',
  concious: 'conscious',
  conciousness: 'consciousness',
  controll: 'control',
  critisism: 'criticism',
  critisize: 'criticize',
  desparate: 'desperate',
  desparately: 'desperately',
  disapear: 'disappear',
  disapeared: 'disappeared',
  disapointing: 'disappointing',
  dissapear: 'disappear',
  dissapointing: 'disappointing',
  embarass: 'embarrass',
  embarassed: 'embarrassed',
  embarassing: 'embarrassing',
  embarrasment: 'embarrassment',
  embarrasement: 'embarrassment',
  enviroment: 'environment',
  enviromental: 'environmental',
  existance: 'existence',
  existant: 'existent',
  familar: 'familiar',
  finaly: 'finally',
  foriegn: 'foreign',
  foriegner: 'foreigner',
  freind: 'friend',
  freinds: 'friends',
  freindly: 'friendly',
  freindship: 'friendship',
  goverment: 'government',
  grammer: 'grammar',
  gaurd: 'guard',
  gaurds: 'guards',
  gaurding: 'guarding',
  guage: 'gauge',
  happend: 'happened',
  harrass: 'harass',
  harrassed: 'harassed',
  harrassment: 'harassment',
  hieght: 'height',
  inteligence: 'intelligence',
  inteligent: 'intelligent',
  interupt: 'interrupt',
  interuption: 'interruption',
  judgement: 'judgment',
  knowlege: 'knowledge',
  knowlegde: 'knowledge',
  knowlegable: 'knowledgeable',
  liason: 'liaison',
  libary: 'library',
  maintainance: 'maintenance',
  maintenence: 'maintenance',
  millenium: 'millennium',
  mispell: 'misspell',
  mispelled: 'misspelled',
  noticable: 'noticeable',
  nuisence: 'nuisance',
  occassion: 'occasion',
  occassional: 'occasional',
  occassionally: 'occasionally',
  oppurtunity: 'opportunity',
  oppurtunities: 'opportunities',
  parralel: 'parallel',
  parrallel: 'parallel',
  particularily: 'particularly',
  peice: 'piece',
  peices: 'pieces',
  percieve: 'perceive',
  percieved: 'perceived',
  perminant: 'permanent',
  perserverance: 'perseverance',
  perseverence: 'perseverance',
  persistant: 'persistent',
  posession: 'possession',
  posessions: 'possessions',
  prefered: 'preferred',
  prefering: 'preferring',
  priviledge: 'privilege',
  priviledged: 'privileged',
  probaly: 'probably',
  probly: 'probably',
  proffesional: 'professional',
  profesional: 'professional',
  profesor: 'professor',
  professer: 'professor',
  publically: 'publicly',
  quater: 'quarter',
  quaters: 'quarters',
  realy: 'really',
  reccomend: 'recommend',
  reccomended: 'recommended',
  recomend: 'recommend',
  recomendation: 'recommendation',
  refered: 'referred',
  refering: 'referring',
  relevent: 'relevant',
  religous: 'religious',
  rember: 'remember',
  rembered: 'remembered',
  rememberance: 'remembrance',
  rythm: 'rhythm',
  rythym: 'rhythm',
  sence: 'sense',
  sieze: 'seize',
  similer: 'similar',
  similiar: 'similar',
  similiarly: 'similarly',
  sincerley: 'sincerely',
  sophmore: 'sophomore',
  speach: 'speech',
  succesful: 'successful',
  sucessful: 'successful',
  sucessfully: 'successfully',
  sucess: 'success',
  suprise: 'surprise',
  suprised: 'surprised',
  suprising: 'surprising',
  surprize: 'surprise',
  tendancy: 'tendency',
  tendancies: 'tendencies',
  threshhold: 'threshold',
  tommorow: 'tomorrow',
  tommorrow: 'tomorrow',
  tounge: 'tongue',
  truely: 'truly',
  unfortunatly: 'unfortunately',
  unfortunatley: 'unfortunately',
  untill: 'until',
  untilll: 'until',
  useable: 'usable',
  useing: 'using',
  vaccum: 'vacuum',
  vaccuum: 'vacuum',
  vehical: 'vehicle',
  visable: 'visible',
  invisable: 'invisible',
  wether: 'whether',
  whcih: 'which',
  wierd: 'weird',
  writting: 'writing',
  yeild: 'yield',
  yeilds: 'yields',
  alot: 'a lot',
  apparant: 'apparent',
  appearence: 'appearance',
  appropiate: 'appropriate',
  basicly: 'basically',
  beggining: 'beginning',
  begining: 'beginning',
  carrer: 'career',
  comparision: 'comparison',
  completly: 'completely',
  concieve: 'conceive',
  concieved: 'conceived',
  curiousity: 'curiosity',
  decieve: 'deceive',
  decieved: 'deceived',
  decison: 'decision',
  decisons: 'decisions',
  desicion: 'decision',
  diference: 'difference',
  diferences: 'differences',
  diferent: 'different',
  dispite: 'despite',
  durring: 'during',
  enought: 'enough',
  enuf: 'enough',
  eqaul: 'equal',
  equiped: 'equipped',
  exagerate: 'exaggerate',
  excede: 'exceed',
  exelent: 'excellent',
  experiance: 'experience',
  experianced: 'experienced',
  explaination: 'explanation',
  feild: 'field',
  forfit: 'forfeit',
  fourty: 'forty',
  garantee: 'guarantee',
  greatful: 'grateful',
  guidence: 'guidance',
  hopefull: 'hopeful',
  humerous: 'humorous',
  ignorence: 'ignorance',
  immediatly: 'immediately',
  independant: 'independent',
  inocent: 'innocent',
  intresting: 'interesting',
  iresistable: 'irresistible',
  irresistable: 'irresistible',
  jist: 'gist',
  liesure: 'leisure',
  lonelyness: 'loneliness',
  loseing: 'losing',
  miniture: 'miniature',
  morgage: 'mortgage',
  ofcourse: 'of course',
  ommit: 'omit',
  ommited: 'omitted',
  origional: 'original',
  parliment: 'parliament',
  passtime: 'pastime',
  pavillion: 'pavilion',
  peculier: 'peculiar',
  personel: 'personnel',
  potatos: 'potatoes',
  preceeding: 'preceding',
  preferance: 'preference',
  presance: 'presence',
  promiss: 'promise',
  questionaire: 'questionnaire',
  reconize: 'recognize',
  recurrance: 'recurrence',
  reguarding: 'regarding',
  resistence: 'resistance',
  responsable: 'responsible',
  responsability: 'responsibility',
  ridiculus: 'ridiculous',
  ridiculos: 'ridiculous',
  rougly: 'roughly',
  saftey: 'safety',
  sandwhich: 'sandwich',
  scisors: 'scissors',
  secratary: 'secretary',
  seige: 'siege',
  shoudl: 'should',
  shudl: 'should',
  somthing: 'something',
  sould: 'should',
  succede: 'succeed',
  tatoo: 'tattoo',
  technicaly: 'technically',
  technicly: 'technically',
  temperture: 'temperature',
  thanksfor: 'thanks for',
  thirteeth: 'thirteenth',
  thnaks: 'thanks',
  thnx: 'thanks',
  thoughout: 'throughout',
  togehter: 'together',
  togther: 'together',
  upadte: 'update',
  upadted: 'updated',
  usualy: 'usually',
  whant: 'want',
  whas: 'was',
  whe: 'when',
  whent: 'went',
  wher: 'where',
  whihc: 'which',
  whihl: 'while',
  whiel: 'while',
  whne: 'when',
  whould: 'would',
  withdrawl: 'withdrawal',
  withing: 'within',
  withold: 'withhold',
  wokr: 'work',
  woudl: 'would',
  wrod: 'word',
  wroet: 'wrote',
  wuld: 'would',
  yera: 'year',
  yeras: 'years',
  yoru: 'your',
  yuor: 'your',
  yuo: 'you',

  // Days of the week
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thursday: 'Thursday',
  friday: 'Friday',
  saturday: 'Saturday',
  sunday: 'Sunday',

  // Tiny ones
  ot: 'to',
  fo: 'of',
  fomr: 'from',
  fropm: 'from',
  goin: 'going',
  knwo: 'know',
  jsut: 'just',
  liek: 'like',
  fpr: 'for',
  abotu: 'about',
  abou: 'about',
  abuot: 'about',
  affraid: 'afraid',
  thign: 'thing',
  thigns: 'things',
  sayd: 'said'
};
